#include <stdio.h>
#include <stdlib.h>
#include <string.h>






void inicio(){
    printf("Bienvenido usuario le predentamos a Arudo Linux");
    printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlcccccccccccccccclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0occccccccccccccccclkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxcccccccccccccccccclkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkccccccccccllccccccclkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlcccccccccldoccccccclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlccccccccclxxlccccccclOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMMMMWNKOkk0XNWWNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lccccccccccxOdccccccccoKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMMMWNKkdlld0NMMNkc:xKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lccccccccccx0klccccccccxXWXKKXWMMMMMMWWWMMMWWMMMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMMMWXOdlcclkkdxkkc':c:xOxxkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlccccccccccxK0occccccccccc;,,:dKMMMMMNOkOKNKO0NMMMMMMMMMM\n
MMMMMMMMMMMMMMMMMMWKkocccclON0c;odo:;c::xKkllx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlccccccccccxKKdcccccc;''';;'.,':kXNMMMNOoldkxodKWMMMMMMMM\n
MMMMMMMMMMMMMMMMWKxlccccclkNMMXo:xKx:cl:,o0OoclxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNklccccccccclxKKxlccc;'.';;;;'':ccccldxk0K0xllolcoONMMMMMMM\n
MMMMMMMMMMMMMMWXkocccccccxXWMMNo.;dOc:ll:,;xkoccxXMMMMMMMMMMMMMMMMMWWWNNNNNWWWWMMMMMMMMMMMMNxcccccccccclkXXOlc:,.';;;;;;,.;ooooolc:;:kXklcccclONMMMMMM\n
MMMMMMMMMMMMMN0occcccccclOWMMMO,.:d0d;colc,,;::clOWMMMMMMMWNK0kxdollllcccclllloodddxkOKXNWWKdcccccccccclOXXOl,.',;;;;;;;,.,ooooool:cxXWNklcccco0WMMMMM\n
MMMMMMMMMMMWXklccccccccco0WN0xlcdOKKOc,looc:,..';xNMMWX0kdol::;;,'.',,,,,,,,,,,;;,;;;;:clodl:;:cccccccco0XKd;',;;;;;;;;;;.,loool;:xXWMMMNklccccxXMMMMM\n
MMMMMMMMMMWKdcccccccccccokxlldO0KKK00x;;loolc;,'.;dkxolc::::::;,..'..',,,,,'''''''''''',,;;,,',,,,;:cccx0kl:::;;;;;;;;;;;.,loool::ox0NWMMNklcccdXMMMMM\n
MMMMMMMMMWKdccccccccccccldocoxO0KKKKK0o';looll::;,'''',,;;;::c:'.,;,.'cllllc:,.,::;;,,'..''''',,,''',,;ll:cc:;;;;;;;;;;;;.,looooolc::cod0NXdcccxXMMMMM\n
MMMMMMMMMXdccccccccccccccxXXOl;cdO0K00kc':loooll:;,'.....;cllc'.,;;;,.,lll:,'..'cllc:,'..,;,,'...',,'.':cl:,,,;;;;;;;;;;,.,ooolclooooc;,dNW0oclOWMMMMM\n
MMMMMMMMWklcccccccccccccclOWMx'.,o0KKK0x;':loooc,'.',;;;,'':c,.,;;;;;'.:c,..';'.:lc;''''.':;'......,;cl:,'......';;;;;;;,.;ooolc;;cc:cdKWMMNxlkNMMMMMM\n
MMMMMMMWKdccccccccccccccccdKXo,cx0KK0K0Od;':c:'.',;;;;;;;;,'..';;;;;;,....,;;;,..,'',;;;..,'.';;;'.,c:'.',;;;;;,..,;;;;;'.:oooool:'.lXMMMMMWXKWMMMMMMM\n
MMMMMMMWOlccccccccccccccc:;:ldk0KKKKKK00kl,...',;;;;;;;;;;;,..;::;;;;;..';;;;;;..';;;;;;'..,;;;;;;,...';;;;;;;;::,..,;;;.'coooooool;;kNMMMMMMMMMMMMMMM\n
MMMMMMMNklcccccccccccccc:,.,cdxkO0KKK00Kkc'.,;;;;;;;;;;;;;;'.;lllcc:;;..,;;;;;;'.';;;;;;,..;;;;;;;;;..';;;;;;;;;:c:..,;,.,loooooooooc:oKWMMMMMMMMMMMMM\n
MMMMMMMNkcccccccccccccccc:;;,,'':clk000x:'';;;;;;;;;;;;;;;,.'llllllc:;..;:;;;;;;',;;;;;;;..,;;;;;;;;;'.';;;;;;;;;:cc'.''.:oooooooooool;lXMMMMMMMMMMMMM\n
MMMMMMMNklcccccccccccccccccccc,.'':kKOo,',;;;;::::cccccc::,.:oddddddoc',odooollllllccccc:,.';;;;::c::;'..;;;;;;;;;:cc'..,looooooooooc;cOWMMMMMMMMMMMMM\n
MMMMMMMWOlcccccccccccccccccccc:..lO0k:'';;;:cclloooodddddo,,okkkkkxxxc,cxxxxxdolllloddool:',;;;clooool:'.';;;;;;;;;:cl'.;oooooooooc,';oKWMMMMMMMMMMMMM\n
MMMMMMMW0occccccccccccccccccc:,'o00x;.,;:cloodddxxxxxxxxxo,;xkkkkkxxd;,odddoolc:::cllllllc:;;;;::ccc::;;..';;;;;;;;;:cl,.:oooooooc;',:lOWMMMMMMMMMMMMM\n
MMMMMMMWKdcccccccccccllccccc:',d00o'';clodxxxxxxxxxxxxxddl':xxxxxddo:';ooolllc:;:cllllllll:;::::::;;;;;;,..,;;;;;;;;;:ll'.coooooolll:,;dXMMMMMMMMMMMMM\n
MMMMMMMMXxcccccccccccdxlccc;.,x00l,;loxxxxxxxxxxxxxxxxdooc':dddoooll,'cooolllc::llloooolllccllllllcc:;;;;,..;;;;;;;;;;:lc.'loooooooooc,:0MMMMMMMMMMMMM\n
MMMMMMMMNkcccccccccccx0klcc:',::;,cdxxxxxxxxxxxxxxxxdol:;'.;loooool:':oooolll:,:llooooollccllllllllllc;;;;..';;;;;;;;;;:l;.;ooooooolc:,,kWMMMMMMMMMMMM\n
MMMMMMMMWkcccccccccccxKKxccccc;.'lxxxxxdoxxxxkxxxdlc;,';cc,;loooooc',looooll:',coooooollccllllllllllllc;;;,..,;;;;;;;;;;cl'.;:;;;;;,,,;ckNMMMMMMMMMMMM\n
MMMMMMMMWOlccccccccclkXX0dccc;';oxxkxd:;lxxxxxdoc;,',:okKKl,looooc,':ooool;'.,cloooooll::lllooooooollllc;;;..';;;;;;;;;;:l:..,'.'::cccccxNMMMMMMMMMMMM\n
MMMMMMMMWOlcccccccccoOXXXOl:,':dxxxo:,;oxxxdolc;'',cdOKNWWk;:llll;co:cool;'',:llooool:',cllloooooooollll:;;,..;;;;;;;;;;;:c'.,,.,cccccccdXMMMMMMMMMMWX\n
MMMMMMMMWklcccccccccd0XXX0l';oxkdl;,;lxxddolc:,.,cxOKNWWWWXo;cll;lKXd:ll;:kKd;cllll:,,';cllllooooooooollc;;;..';;;;;;;;;;;c;.',.'cccccccdXMMMMMMMMWKko\n
MMMMMMMMNkccccccccclkKXXkl:lxxoc;,:ldddoollc;'.:dk0NWWWWWWWKl:c:lKWWKl,;l0WWKl;ll:;:xK0o:;:lllloooooooolc:;;'..;;;;;;;;;;;::..,.'cccccccdXMMMMMMWKkocc\n
MMMMMMMMXdccccccccco0Kkl:ldoc,';codddollllc;.'lxOXNWWWWWWWWW0c;dKWWWWOldXWWWWO:,;:xXWWWWKkl:;cllooooooollc;;,..,;;;;;;;;;;;:..,.'cccccccxNMMMMWKkocccc\n
MMMMMMMW0occcccccccooc:clccc,.:oooooloollc;.,lk0NWWWWWWWWWWWWK0NWWWWWWWWWWWWWNOdkXWWWWWWWWNKxl:;clloooollc;;;..';;;;;;;;;;;:'.'.;xoccccckNMMWKkocccccc\n
MMMMMMMNxccccccc:;,;;:clox0Kl,lolllooollc;.'okKNWWWWN0OXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN000xc;,:cllllc:;;'..;;;;;;;;;;;;'..'o0xcccclOWWXkocccccccc\n
MMMMMMW0occcc:;'..;loxOKXXXKc,clllooolll:''lkXWWWWWWXc'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK::KWNOl;,,;:ll:;;,..;;;;;;;;;;;;...,xKxccccoKXOocccccccccc\n
MMMMMMXxccccc;'';oOXXXXXXXX0c,clloooolll,.:kXWWWWWWNK: 'd0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNO' :k0K0kdl:;,,'',,..,;;;;;;;;;;;...,kXxlcccdkdlccccccccccc\n
MMMMMNklcccccccco0XXXXXXXXXKc'cllooolllc''dKWWWWN0o;'.....';o0NWWWWWWWWWWWWWWWWWWWWWWWWN0o;......',:ldxxdl:;,,..,;;;;;;;;;;,...;OXxccccllcccccccccccod\n
MMMMWOlcccccccclkXXXXXXXXXXXo,:llooolllc';0NWWWKl..,codddlc,..lKWWWWWWWWWWWWWWWWWWWWWWKl..,codddoc,..,oxxxxxxo,.,;;;;;;;;;;'...:0KxcccccccccccccloxO0X\n
MMMW0occcccccclxKXXXXXXXXXNXk;,llooolll:'lXWWWK:.;x0KKK00Okxo'.:KWWWWWWWWWWWWWWWWWWWWK:.:OXNXXK0Okxo' 'lxxxxxd,.,;;;;;;;;;;..''lKKxccccccccccloxOKXXXX\n
MMW0occcccccccxKXXXXXXXXXXXXKl'clooooll:'oNWWNo.,KMMMMMMWWNKOo..oNWWWWWWWWWWWWWWWWWWNo.,KMMMMMMMWX0ko. ;dxxxxo'.,;;;;;;;;;,..''oX0dcccccccloxOKXXXXXXX\n
MW0occcccccccd0XXXXXXNXXXXXXXO:,lloooll:'oNNNXc cNMMMMMMMMMMNO, cNWWWWWWWWWWWWWWWWWWNl :XMMMMMMMMMWXx' 'oddxxl..;;;;;;;;;;..','xXOocccccldOKXXXXXXXXXX\n
NOoccccccccco0XXXXXXXXXXXXXXXXx;;lllollc,lXNNXo.'OWMMMMMMMMMMO..dNWWWWWWWWWWWWWWWWWWNx..OMMMMMMMMMMWx. ;odddd:.';;;;;;;;;'..;';kKxlcclok0XXXXXXXXXXXXX\n
klcccccccccoOXXXXXXXXXXXXXXXXXKc.;llllll;:0NXX0c.'xNMMMMMMMNx'.lKNNWWWWWWWWWWWWWWWWNNKl.'xXMMMMMMMNx'.,lddddo'.,;;;;;;;;,..,;':00dcldOKXXXXXXXXXXXXXXX\n
lcccccccccoOXXXXXXXXXXXXXXXXXXKc..;lllllc,oXXXX0d,.,lxkOkxl,.,dKXNNNWWWWWWWWWWWWWWWNNXKd,.'cdkkkdc'.':oooddd:.';;;;;;;;,..,;,'oKkodOKXXXXXXXXXXXXXXXXX\n
cccccccccoOXXXXXXXXXXXXXXXXXXXKl',.,colll;;xXXKXK0xc;''''';cx0XXXNNNWWWWWWWWWWWWWWNNXXXK0xl;,''',;lxkdoooodc..,;;;;;;;'..,;;',xKOOKXXXXXXXXXXXXXXXXXXX\n
ccccccccoOXXXXXXXXXXXXXXXXXXXXXl,:;'.;loll;:kKKKKKKKKK0000KKKKXXXXNNNWWWWWWWWWWWWWNNXXKKKKKKK000KKK0koooodl'.,;;;;;;,...,;;;':0XXXXXXXXXXXXXXXXXXXXXXX\n
cccccccoOXXXXXXXXXXXXXXXXXXXXXXo,clc,.';lol;:xKKKKKKKKKKKKKKKKXXXXNNNWWWWWWWWWWWWWNNXXXKKKKKKKKKKKKkdooool,.,;;;;;,....';;;,'dXNXXXXXXXXXXXXXXXXXXXXXX\n
ccccccd0XXXXXXXXXXXXXXXXXXXXXXXx,:ool:,.',:c:;o0KKKKKKKKKKKKK0O0XNNNWWWWWWWWWWWWWWWNX0OO0KKKKKKKK0kdooool,.,;;;;,...,'.,;;;':0XXXXXXXXXXXXXXXXXXXXXXXX\n
cccclxKXXXXXXXXXXXXXXXXXXXXXXXXk;:oooolc;'..,,,:x0KKKKKKKKXKK0kddxk0KXNNWWWWWWNXK0OkkxkOKKKKKKKK0kdooooc'.,;;,'..',;;..,;;,,xXXXXXXXXXXXXXXXXXXXXXXXXX\n
cccokKXXXXXXXXXXXXXXXXXXXXXXXXX0:;ooooooll:,cl:'.:x0KKXKKKXXXXXXKOkkOO0XWWWWWNKOOOO0XNNXXXXXKK0kddoooo:'',,'...,;;;;,.';;,'lKXXXXXXXXXXXXXXXXXXXXXXXXX\n
cld0XXXXXXXXXXXXXXXXXXXXXXXXXXXXo,ldooooolc;xNXOxllxKXXXXXXXXXNNNWWWWWWWWWWWWWWWWWWWWWNNNXXK0kxdoodoc'..,'..,;;;;;;;'.,;,'c0XXXXXXXXXXXXXXXXXXXXXXXXXX\n
lkKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO;:dooooooc,lXNNNNXXXXXXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWNX0kxddddddoc:clol,,;;;;;;;,..;;'c0XXXXXXXXXXXXXXXXXXXXXXXXXXX\n
0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXd,cdoooool;'lOXNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWNNK0kxxxxxxddxxxxxdo;',;;;;;;;'.',,l0XXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKo,cdoooolc'.,cokKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKOkxxxxxxxxxxxxdoc;,..';;;;;;;;..';dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd;:ooooll:..,'.,lxk0XNWWWWWWWWWWWWWWWWWWWWWNXK0kxxxxxxxxxxxdlcc:c,..,..;;;;;;;:,.'lOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOl;:cllll;..'cxOOxdddxxkO0XNNWWWWWWNNXKK0Okxxxxdddoolcc::ccloxOKx'...,;;;;;;::';xKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOoc;;:ll,.lKXXXXXXKOkxdddddddddollcc:::::::;;:cclllodxO0XXXXXN0;..,;;;;;:c:;l0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKOdc:;,.,xXXXXXXXXXXXXXXK0ko;';ccccccclll:';dOKXXXXXXXXXXXXXx..,;;;;:;;:cxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKOxoldKXXXXXXXXXXXXXOo:'..lxxxxxxxxxxl...':lkKXXXXXXXXXO;.',,,,;cldOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd,....'oxxxxxxxxxxc.......c0XXXXXXXXxcclodxk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0c.....;dkkkkkkOO00o.....'..;lkXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd,.''..:OXXNNNNNKkl'...'.....,xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXd'.''''..,oKNK0kl,. ..'''....,dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'....'''...,:,......''''......'oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0o,..'....''.........'''''........oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd,.''''''...........'''''''.....'..oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:..'''''''''....''....''......'''''.'oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk;.'''''''''''.....'........''''''''''..oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk,.'''''''''''...''.......''''''''''''''.'xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0:.''''''''''''...''''....''''''''''''''''.;OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKo..''''''''''''..'''''''....''''''''''''''..oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk,.'''''''''''''..'''''''''..'''''''''''''''.:0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXd''''''''''''''...'''''''''..'''''''''''''''.;OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n")
}
